DROP SCHEMA PUBLIC CASCADE ;

DROP TABLE IF EXISTS order_lines CASCADE;
DROP TABLE IF EXISTS orders;

DROP SEQUENCE IF EXISTS jada1;
CREATE SEQUENCE jada1 AS INTEGER START WITH 1 INCREMENT BY 1;

CREATE TABLE orders
(
    id           BIGSERIAL PRIMARY KEY,
    order_number VARCHAR(255) NOT NULL,
    total        DOUBLE PRECISION DEFAULT 0.00
);

CREATE TABLE order_lines
(
    id          BIGSERIAL PRIMARY KEY,
    order_id    BIGINT         NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    description VARCHAR(255)   NOT NULL,
    price       DOUBLE PRECISION NOT NULL
);
